import streamlit as st
import pandas as pd
from cortex import conn

def seed_cortex():
    data = {
        "Topic": [
            # --- AI & LLM (35) ---
            "Large Language Model", "LLM Hallucination", "Context Window", "RAG Synthesis", "AI Tokenization",
            "Neural Network", "Transformer Architecture", "Attention Mechanism", "Deep Learning", "Machine Learning",
            "Supervised Learning", "Unsupervised Learning", "Reinforcement Learning", "Generative AI", "Zero-shot Learning",
            "Few-shot Learning", "AI Prompt Engineering", "Temperature Setting", "Top-P Sampling", "Fine-tuning",
            "Edge AI", "Computer Vision", "Natural Language Processing", "AI Bias", "Turing Test 2.0",
            "AGI Timeline", "AI Singularity", "Ethical AI", "Model Quantization", "GPU Acceleration",
            "TPU vs GPU", "Inference Speed", "Multimodal AI", "AI Safety Guardrails", "Algorithm Transparency",
            
            # --- 3D PRINTING (35) ---
            "Bambu Lab A1 mini", "Bambu Studio", "OrcaSlicer", "PEI Build Plate", "First Layer Calibration",
            "Active Flow Compensation", "Filament Tangle Sensor", "Hotend Nozzle Swap", "Hardened Steel Nozzle", "0.4mm vs 0.6mm Nozzle",
            "PLA Printing", "PETG Stringing", "ABS Warping", "TPU Flex printing", "PVA Supports",
            "3D Printing Clogs", "Cold Pull Method", "Heat Creep", "Z-Offset Tuning", "E-Step Calibration",
            "3D Print Delamination", "Brim vs Raft", "Tree Supports", "Gyroid Infill", "Input Shaping",
            "Linear Advance", "Resin vs FDM", "SLA Curing", "Filament Drying", "Humidity Sensor",
            "Enclosure Cooling", "Bed Leveling", "Extruder Gear Cleaning", "3D Printing Tolerances", "CAD Design for 3D",
            
            # --- ANDROID & KOTLIN (35) ---
            "Kotlin Null Safety", "Kotlin Coroutines", "Jetpack Compose", "Android Lifecycle", "ViewModel Pattern",
            "Dependency Injection", "Retrofit API", "Room Database", "Material 3 Design", "Android Studio Iguana",
            "Kotlin Val vs Var", "Kotlin Data Classes", "Lambda Expressions", "Higher-Order Functions", "Kotlin Sealed Classes",
            "Compose State Management", "Composable Functions", "Modifier Pattern", "Scaffold Layout", "LazyColumn vs RecyclerView",
            "Android Permissions", "Manifest File", "Gradle Build System", "Proguard & R8", "APK vs AAB",
            "Google Play Console", "Firebase Integration", "Android Debug Bridge", "Logcat Debugging", "Android Emulator",
            "SDK Versioning", "Native vs Cross-platform", "Dagger Hilt", "Koin Framework", "Compose Navigation",
            
            # --- PC HARDWARE & TECH (35) ---
            "DDR5 RAM", "NVMe Gen5 SSD", "RTX 50-series", "Ryzen 9000", "LGA 1851 Socket",
            "Thermal Paste Application", "AIO Liquid Cooling", "Airflow Optimization", "Bottleneck Calculator", "Overclocking Safety",
            "BIOS Flashing", "XMP/EXPO Profiles", "PCIe Lanes", "Thunderbolt 5", "USB 4.0",
            "OLED vs IPS", "Refresh Rate Sync", "DisplayPort 2.1", "Power Supply Tier List", "80 Plus Gold",
            "Linux Kernel", "Windows 12 Features", "MacOS Sequoia", "BIOS vs UEFI", "SATA vs NVMe",
            "Mechanical Keyboards", "Optical Switches", "Gaming Mouse Polling", "Ethernet Cat8", "Wi-Fi 7",
            "Bluetooth 5.4", "VR Headsets", "Steam Deck Hardware", "Raspberry Pi 5", "Single Board Computers",
            
            # --- SPACE & SCIENCE (30) ---
            "Starship IFT-7", "Artemis III Moon Mission", "James Webb Deep Field", "Europa Clipper", "Mars Oxygen Gen",
            "Nuclear Fusion Ignition", "Quantum Entanglement", "Standard Model of Physics", "String Theory", "General Relativity",
            "Black Hole Singularity", "Event Horizon", "Time Dilation", "Dark Matter Evidence", "Entropy",
            "Photosynthesis efficiency", "CRISPR Gene Editing", "mRNA Technology", "Global Warming 2026", "Ocean Acidification",
            "Renewable Energy Grid", "Solid-State Batteries", "Perovskite Solar", "Hydroponics", "Vertical Farming",
            "Voyager Interstellar Message", "Hubble Constant", "Exoplanet Atmosphere", "Search for SETI", "Dyson Sphere",

            # --- WORLD & BUSINESS (30) ---
            "3D Printing Business", "E-commerce Strategy", "Digital Marketing 2026", "SEO for AI Search", "Personal Branding",
            "Content Synthesis", "Financial Literacy", "Stock Market AI", "Cryptocurrency Trends", "Blockchain Utility",
            "Remote Work Culture", "Gig Economy", "Entrepreneurship", "Public Speaking", "Networking Skills",
            "Time Management AI", "Emotional Intelligence", "Stoic Leadership", "Growth Mindset", "Critical Thinking",
            "Toronto Tech Scene", "Canada Innovation", "Global Trade 2026", "Sustainable Living", "Mental Health Tech",
            "Future of Education", "Skill Upskilling", "Knowledge Management", "Data Privacy Laws", "Digital Nomadism"
        ],
        "Meaning": [
            # AI & LLM
            "A type of AI trained on vast text data to predict and generate human-like language.",
            "When an AI generates confident but factually incorrect or nonsensical information.",
            "The limit of how much text an AI can process and remember in a single interaction.",
            "Retrieval-Augmented Generation: linking AI to a knowledge base for more accurate answers.",
            "Breaking text into smaller chunks (tokens) that the computer can understand and process.",
            "A series of algorithms that mimic the human brain to recognize patterns in data.",
            "The neural architecture that allows AI to process sequences using 'attention'.",
            "A mechanism that lets AI focus on the most important parts of a sentence simultaneously.",
            "A subset of AI that uses multi-layered neural networks for complex pattern recognition.",
            "The study of algorithms that improve automatically through experience and data.",
            "Training a model on labeled data where the answer is already known.",
            "Finding hidden patterns or structures in data that has no labels.",
            "Learning through trial and error to achieve a goal based on rewards and penalties.",
            "AI capable of creating new content like text, images, music, or code.",
            "The ability of a model to perform a task it wasn't specifically trained for.",
            "Giving a model a few examples to help it understand a specific task.",
            "The art of crafting inputs to get the most accurate and useful response from an AI.",
            "A setting that controls the randomness of AI output; 0 is literal, 1 is creative.",
            "A technique to limit AI choices to the most likely words for better coherence.",
            "Taking a pre-trained model and training it further on a specific dataset.",
            "Running AI models directly on a local device rather than in the cloud.",
            "AI's ability to interpret and understand visual information from the world.",
            "The branch of AI focused on the interaction between computers and human languages.",
            "Prejudices in AI data that lead to unfair or skewed results.",
            "A modern test assessing if AI can truly reason or just mimic patterns.",
            "The predicted point when AI reaches human-level intelligence across all domains.",
            "The theoretical future point where AI growth becomes uncontrollable and irreversible.",
            "Developing AI with a focus on safety, fairness, and human benefit.",
            "Reducing model size so it can run on smaller hardware with less power.",
            "Using Graphics Processing Units to handle the heavy math required for AI training.",
            "Tensor Processing Units are custom Google chips optimized for AI specifically.",
            "The time it takes for a model to generate a response after receiving an input.",
            "AI that can process and combine different types of data like text, audio, and video.",
            "Safety layers built into AI to prevent harmful, illegal, or biased outputs.",
            "The practice of making AI decision-making processes understandable to humans.",

            # 3D PRINTING
            "A high-speed desktop 3D printer with automatic calibration and a cantilever design.",
            "The official slicer for Bambu Lab printers, based on PrusaSlicer and Slic3r.",
            "An open-source slicer popular for high-speed printing and advanced calibrations.",
            "Polyetherimide coating on a steel plate that provides excellent bed adhesion when hot.",
            "The most critical part of a print; requires a clean bed and perfect nozzle height.",
            "A feature that detects and compensates for internal pressure to ensure smooth extrusion.",
            "A sensor that pauses the print if the filament gets stuck or knotted on the spool.",
            "The process of replacing the nozzle assembly, often easier on Bambu machines.",
            "A durable nozzle capable of printing abrasive materials like carbon fiber or glow-in-the-dark.",
            "0.4mm is standard; 0.6mm is faster and better for filled filaments but less detailed.",
            "Polylactic Acid: the most common, eco-friendly, and easiest filament to print.",
            "Polyethylene Terephthalate Glycol: strong and heat resistant, but requires high retraction.",
            "Acrylonitrile Butadiene Styrene: strong but toxic fumes and high shrinkage (needs enclosure).",
            "Thermoplastic Polyurethane: a flexible material that requires slow, direct-drive extrusion.",
            "Polyvinyl Alcohol: a water-soluble support material used for complex geometries.",
            "Obstructions in the hotend that prevent filament from extruding properly.",
            "A maintenance technique to clear clogs by pulling filament out while semi-cool.",
            "When heat travels up the cooling assembly, causing filament to melt too early.",
            "The fine-tuning of the distance between the nozzle and the build plate.",
            "The calibration of the extruder motor to ensure it pushes the exact amount of filament.",
            "When layers fail to bond together, often due to low temperatures or high cooling.",
            "A brim adds a thin outer layer for adhesion; a raft builds a base under the part.",
            "Organic-looking supports that save material and are easier to remove than standard blocks.",
            "An infill pattern that is strong in all directions and prevents internal vibrations.",
            "A technique to reduce ghosting and ringing at high printing speeds.",
            "Ensures the extruder pressure stays constant during speed changes for better corners.",
            "SLA uses liquid resin and UV light for extreme detail; FDM melts plastic layers.",
            "The process of using UV light to fully harden a resin print after it is washed.",
            "Using a dedicated dryer to remove moisture from filament for better print quality.",
            "A device to monitor the moisture level inside a filament dry-box.",
            "Controlling the air temperature around a print to prevent warping in high-temp materials.",
            "Ensuring the build plate is perfectly flat relative to the nozzle's path.",
            "Removing plastic dust and debris from the drive gears to prevent slipping.",
            "The small gaps required in a design to ensure moving parts fit together after printing.",
            "Designing parts with 45-degree angles to minimize the need for support material.",

            # ANDROID & KOTLIN
            "Features that prevent the 'Billion Dollar Mistake' of null pointer exceptions.",
            "A way to write asynchronous code that doesn't block the main UI thread.",
            "Android's modern toolkit for building native UI using declarative Kotlin code.",
            "The stages an app goes through (onCreate, onStart, onResume, etc.).",
            "A class that stores and manages UI-related data in a lifecycle-aware way.",
            "Providing objects a class needs rather than letting it create them (e.g., Hilt).",
            "A type-safe HTTP client for Android and Java to handle network requests.",
            "An abstraction layer over SQLite for more robust local database management.",
            "The latest evolution of Material Design with dynamic color and updated components.",
            "The latest stable version of Android Studio with enhanced AI coding features.",
            "Val is read-only (immutable); Var is mutable and can be reassigned.",
            "Classes specifically designed to hold data, providing auto-generated methods like equals().",
            "Short blocks of code that can be passed as arguments or returned from functions.",
            "Functions that take other functions as parameters or return them.",
            "A way to define restricted class hierarchies for better type safety and logic.",
            "Using 'remember' and 'mutableStateOf' to update the UI when data changes.",
            "Functions annotated with @Composable that define a piece of the app's UI.",
            "An object used to decorate or provide extra logic to Composable elements.",
            "A top-level Composable that provides a slot API for common UI parts (TopBar, Fab).",
            "LazyColumn only renders items visible on screen, much faster than a standard list.",
            "The system that protects user privacy by requiring consent for features like camera or GPS.",
            "The file that defines the app's package name, components, and permissions.",
            "The tool used to compile and build Android projects into executable files.",
            "Tools used to shrink, obfuscate, and optimize your app's code for release.",
            "APK is for direct installation; AAB is the optimized format for the Play Store.",
            "The platform used to publish and manage Android apps for users worldwide.",
            "Google's platform for mobile development, offering auth, database, and analytics.",
            "A command-line tool that lets you communicate with a connected Android device.",
            "The tool in Android Studio used to view real-time system and app logs.",
            "A virtual device used to test apps on different screen sizes and Android versions.",
            "The specific version of the Android API your app is built to support.",
            "Native is built for one OS; Cross-platform (like Flutter) works on multiple.",
            "A dependency injection library for Android that reduces boilerplate code.",
            "A lightweight dependency injection framework specifically for Kotlin.",
            "A library for handling screen-to-screen movement in a Compose-based app.",

            # PC HARDWARE
            "The latest generation of system memory, offering higher speeds and lower voltage.",
            "Solid State Drives that use the PCIe 5.0 interface for extreme data transfer speeds.",
            "NVIDIA's expected 2025/2026 GPU lineup for high-end gaming and AI tasks.",
            "AMD's latest desktop processors based on the Zen 5 architecture.",
            "The new socket for Intel's Arrow Lake processors, requiring new motherboards.",
            "The material used to fill gaps between the CPU and the cooler for heat transfer.",
            "All-In-One liquid coolers that use a pump and radiator to chill the CPU.",
            "The direction of air through a case, usually front-to-back and bottom-to-top.",
            "When one component (like an old CPU) limits the performance of a faster one (like a GPU).",
            "Increasing component clock speeds, requiring better cooling and stable power.",
            "Updating the motherboard's core software to support newer CPUs or features.",
            "Pre-set overclocking profiles for RAM to reach its advertised speeds.",
            "The data paths that connect the CPU to high-speed components like GPUs and SSDs.",
            "The latest cable standard offering up to 80Gbps of bi-directional data transfer.",
            "A high-speed USB standard that matches Thunderbolt capabilities.",
            "OLED offers perfect blacks and colors; IPS offers better brightness and longevity.",
            "Technologies like G-Sync and FreeSync that eliminate screen tearing in games.",
            "The newest monitor connection standard supporting high resolutions and refresh rates.",
            "A ranked list of power supplies based on reliability and component quality.",
            "A rating that indicates a power supply is at least 87% efficient under load.",
            "The core of the Linux operating system, used in Android, servers, and PCs.",
            "The anticipated 2025/2026 OS release from Microsoft with deep AI integration.",
            "The latest Apple desktop OS, featuring iPhone mirroring and AI tools.",
            "UEFI is the modern, graphical version of the old text-based BIOS system.",
            "SATA is limited to 600MB/s; NVMe can reach over 10,000MB/s.",
            "Keyboards that use physical switches for better durability and tactile feel.",
            "Switches that use light beams for faster response times and no 'debounce' delay.",
            "How often a mouse reports its position to the PC, usually 1000Hz to 8000Hz.",
            "A high-speed networking cable capable of 40Gbps over short distances.",
            "The newest wireless standard using the 6GHz band for ultra-low latency.",
            "The latest Bluetooth version with improved stability and lower power usage.",
            "Devices like the Quest 3 or Vision Pro that provide immersive digital worlds.",
            "Valve's handheld PC that popularized portable AAA gaming on Linux.",
            "The latest version of the popular SBC, featuring a much faster processor.",
            "Small, low-power computers used for DIY projects, servers, and automation.",

            # SPACE & SCIENCE
            "The latest test flight of the world's largest and most powerful rocket.",
            "The NASA mission planned to return humans to the lunar surface.",
            "Images from the JWST showing the universe as it was billions of years ago.",
            "A mission to study Jupiter's moon Europa and search for signs of life.",
            "Using MOXIE technology to turn Mars' CO2 atmosphere into breathable oxygen.",
            "A major milestone where a fusion reaction produced more energy than it consumed.",
            "A phenomenon where particles stay connected regardless of distance.",
            "The theory describing three of the four known fundamental forces of nature.",
            "A theoretical framework where particles are replaced by one-dimensional strings.",
            "Einstein's theory that gravity is the result of the curvature of spacetime.",
            "A point of infinite density at the center of a black hole.",
            "The 'point of no return' around a black hole where light cannot escape.",
            "The difference in elapsed time between two clocks due to relative velocity or gravity.",
            "Non-luminous matter detected by its gravitational effects on visible stars.",
            "A measure of disorder or randomness in a system, which always increases over time.",
            "Recent breakthroughs in engineering plants to capture more solar energy.",
            "A technology used to edit genes with high precision, treating genetic diseases.",
            "A vaccine technology that teaches cells how to make a protein to trigger an immune response.",
            "The ongoing rise in Earth's temperature and its impact on global weather.",
            "The ongoing decrease in the pH of the Earth's oceans, caused by CO2 uptake.",
            "A modernized electrical system that can handle fluctuating solar and wind power.",
            "Next-gen batteries that use solid electrolytes for more safety and higher capacity.",
            "A new type of solar cell that is cheaper and more efficient than silicon.",
            "Growing plants in a nutrient-rich water solution without the use of soil.",
            "Growing crops in vertically stacked layers, often in controlled urban environments.",
            "A golden record on Voyager 1 containing sounds and images of Earth.",
            "A unit that describes how fast the universe is expanding at different distances.",
            "The gases surrounding a planet outside our solar system, searched for life signs.",
            "The Search for Extraterrestrial Intelligence using radio telescopes.",
            "A theoretical mega-structure that completely encompasses a star to capture its energy.",

            # WORLD & BUSINESS
            "Starting a business by selling custom 3D printed parts on platforms like Etsy.",
            "The method of selling goods online through optimized stores and social media.",
            "Using AI and data analytics to reach specific customers more effectively.",
            "Optimizing content so that AI search engines recommend your site.",
            "Building a public reputation around your skills and unique knowledge.",
            "Using AI tools to summarize complex data into easy-to-read reports.",
            "The set of skills and knowledge that allows an individual to manage money.",
            "Using machine learning models to predict market trends and stock movement.",
            "The use of digital currencies and their adoption in the global economy.",
            "A digital ledger that provides a secure, transparent way to record transactions.",
            "The shift toward working from home or anywhere using digital tools.",
            "A labor market characterized by short-term contracts or freelance work.",
            "The activity of setting up a business and taking on financial risks for profit.",
            "The art of communicating information to a live audience effectively.",
            "Building long-term relationships for mutual business or career benefit.",
            "Using AI to schedule tasks and prioritize the most important work.",
            "The capacity to be aware of, control, and express one's emotions.",
            "Using ancient wisdom to stay calm and focused in high-pressure business.",
            "The belief that intelligence can be developed through persistence and learning.",
            "The ability to analyze facts objectively to form a calculated judgment.",
            "The growing cluster of startups and tech giants located in the GTA.",
            "Canada's focus on green energy, AI research, and tech immigration.",
            "The interconnected nature of the world's economies and supply chains.",
            "Making lifestyle choices that reduce your personal environmental impact.",
            "Using apps and wearable tech to track and improve mental well-being.",
            "The shift toward personalized, AI-driven learning in schools and universities.",
            "Continuously learning new skills to stay relevant in a changing job market.",
            "The process of capturing, distributing, and effectively using knowledge.",
            "The evolving set of rules that protect how your personal data is used online.",
            "The lifestyle of people who work remotely while traveling the world."
        ]
    }
    
    df = pd.DataFrame(data)
    
    try:
        current_ctx = conn.read(worksheet="Context", ttl="1s")
        # Combine and remove duplicates
        updated_ctx = pd.concat([current_ctx, df]).drop_duplicates(subset=['Topic'], keep='last')
        conn.update(worksheet="Context", data=updated_ctx)
        st.success(f"Cortex Infused! {len(df)} High-Value Nodes added to the Onion.")
    except Exception as e:
        st.error(f"Infusion Failed: {e}")

st.title("🧪 Neural Infusion Utility")
st.markdown("This will upload 200 tracks to the Onion's Synthesis brain.")
if st.button("START INFUSION"):
    seed_cortex()
